name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.0.1
    - name: Build
      run: cargo build --verbose
  clippy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.0.1
    - name: Clippy
      run: cargo clippy --verbose
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.0.1
    - name: Run tests
      run: cargo test --verbose
  release:
    runs-on: ubuntu-latest
    needs: [test, clippy, format]
    steps:
    - uses: actions/checkout@v1
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.DOCKERHUB_USERNAME }}"
        password: "${{ secrets.DOCKERHUB_TOKEN }}"
        image_name: stock_exporter
        image_tag: latest
